In [ ]:
!pip install tensorflow
!pip install tensorflow-text
!pip install spacy
!pip install contractions
!pip install emoji
!pip install emot
!pip install demoji
!pip install nlpaug

  Obtaining dependency information for typing-extensions<4.6.0,>=3.6.6 from https://files.pythonhosted.org/packages/31/25/5abcd82372d3d4a3932e1fa8c3dbf9efac10cc7c0d16e78467460571b404/typing_extensions-4.5.0-py3-none-any.whl.metadata
  Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.11.0
    Uninstalling typing_extensions-4.11.0:
      Successfully uninstalled typing_extensions-4.11.0


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic 2.6.1 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
pydantic-core 2.16.2 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
torch 2.2.0 requires typing-extensions>=4.8.0, but you have typing-extensions 4.5.0 which is incompatible.
typeguard 4.2.1 requires typing-extensions>=4.10.0; python_version < "3.13", but you have typing-extensions 4.5.0 which is incompatible.
ERROR: Could not find a version that satisfies the requirement tensorflow-text (from versions: none)
ERROR: No matching distribution found for tensorflow-text


  Obtaining dependency information for typing-extensions>=4.6.1 from https://files.pythonhosted.org/packages/01/f3/936e209267d6ef7510322191003885de524fc48d1b43269810cd589ceaf5/typing_extensions-4.11.0-py3-none-any.whl.metadata
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.5.0
    Uninstalling typing_extensions-4.5.0:
      Successfully uninstalled typing_extensions-4.5.0


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.11.0 which is incompatible.


In [ ]:
!pip install transformers==4.30.2
!pip install simpletransformers

  Obtaining dependency information for transformers==4.30.2 from https://files.pythonhosted.org/packages/5b/0b/e45d26ccd28568013523e04f325432ea88a442b4e3020b757cf4361f0120/transformers-4.30.2-py3-none-any.whl.metadata
  Using cached transformers-4.30.2-py3-none-any.whl.metadata (113 kB)
  Obtaining dependency information for tokenizers!=0.11.3,<0.14,>=0.11.1 from https://files.pythonhosted.org/packages/62/41/93d3135ec30f596a71490ce11a73572190fe80e85a2aea18f116a520cc41/tokenizers-0.13.3-cp311-cp311-win_amd64.whl.metadata
  Using cached tokenizers-0.13.3-cp311-cp311-win_amd64.whl.metadata (6.9 kB)
Using cached transformers-4.30.2-py3-none-any.whl (7.2 MB)
Using cached tokenizers-0.13.3-cp311-cp311-win_amd64.whl (3.5 MB)
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.15.2
    Uninstalling tokenizers-0.15.2:
      Successfully uninstalled tokenizers-0.15.2


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\User\\anaconda3\\Lib\\site-packages\\~2kenizers\\tokenizers.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



  Obtaining dependency information for tokenizers from https://files.pythonhosted.org/packages/c1/02/40725eebedea8175918bd59ab80b2174d6ef3b3ef9ac8ec996e84c38d3ca/tokenizers-0.15.2-cp311-none-win_amd64.whl.metadata
  Using cached tokenizers-0.15.2-cp311-none-win_amd64.whl.metadata (6.8 kB)
Using cached tokenizers-0.15.2-cp311-none-win_amd64.whl (2.2 MB)
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.13.3
    Uninstalling tokenizers-0.13.3:
      Successfully uninstalled tokenizers-0.13.3


In [ ]:
from simpletransformers.classification import ClassificationModel, ClassificationArgs
import pandas as pd

import spacy
from nltk import word_tokenize
from nltk.corpus import stopwords
import string
import contractions
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
import re
from nltk.tokenize import TweetTokenizer
import regex
import nltk
from nltk.stem import SnowballStemmer
import demoji
import emoji
from sklearn.metrics import f1_score
import os
# os.environ["MODEL_DIR"] = '/content/drive/MyDrive/homo/Model'
# import nlpaug.augmenter.char as nac
# import nlpaug.augmenter.word as naw
from nlpaug.util import Action
demoji.download_codes()
lemmatizer = WordNetLemmatizer()
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report,accuracy_score
from sklearn.svm import LinearSVC

C:\Users\User\AppData\Local\Temp\ipykernel_6968\183952326.py:24: FutureWarning: The demoji.download_codes attribute is deprecated and will be removed from demoji in a future version. It is an unused attribute as emoji codes are now distributed directly with the demoji package.
  demoji.download_codes()


In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('whitespace')
nltk.download('wordnet')
nltk.download('omw-1.4')
stop_words = set(stopwords.words("english","spanish"))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Error loading whitespace: Package 'whitespace' not found
[nltk_data]     in index
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
df_train_Eng = pd.read_csv('Task 2 Training set (English).csv')
df_val_Eng=pd.read_csv('val.csv')
df_train_span=pd.read_csv('train.csv')
df_val_span=pd.read_csv('val (1).csv')

In [ ]:
df_train_Eng.head()

text    binary  \
0  #USER# #USER# I'm really liking this project, ...      Hope   
1  #USER# Oh shit really? I would hope they'd she...      Hope   
2  #USER# Good morning, Bud! 🥰 Another good decis...      Hope   
3  i aspire to have the level of delusion to beli...      Hope   
4  #USER# #USER# Projects are continuously attack...  Not Hope   

         multiclass    id  
0    Realistic Hope  5820  
1  Generalized Hope  4061  
2  Generalized Hope  1621  
3  Unrealistic Hope  1754  
4          Not Hope   401

In [ ]:
df_train_span.head()

text    binary  \
0  Mientras me persigno y le rezo a la Virgen del...  Not Hope   
1  No.. Yo ya no estoy para esperar.. Ni para rog...  Not Hope   
2  Creo que estamos ante el mejor episodio de est...      Hope   
3  Bueno ojalá q cuando llegue este fin de semana...      Hope   
4  #USER# #USER# Marcos de boludo no tiene un pel...  Not Hope   

         multiclass    id  
0          Not Hope  5533  
1          Not Hope   549  
2  Generalized Hope  4350  
3    Realistic Hope  3593  
4          Not Hope   770

In [ ]:
df_test_Eng=pd.read_csv('test - no_label.csv')
df_test_span=pd.read_csv('Task2_ES_test_no_label.csv')

In [ ]:
frame1=(df_train_Eng,df_train_span)
combined_train=pd.concat(frame1)
frame2=(df_val_Eng,df_val_span)
combined_val=pd.concat(frame2)
frame3=(df_test_Eng,df_test_span)
combined_test=pd.concat(frame3)

In [ ]:
from sklearn.utils import shuffle

In [ ]:
combined_train=shuffle(combined_train)

In [ ]:
combined_val=shuffle(combined_val)

In [ ]:
combined_test=shuffle(combined_test)

In [ ]:
combined_train.to_csv('train1_data.csv')

In [ ]:
combined_test

text    id
468  RT #USER# Cantar el himno de mi tierra ha sido...  5712
849  Key raise can political letter. Congress lead ...  6160
856  #USER# #USER# #USER# #USER# Keep it going I sa...  7136
4    RT #USER# Quiero deseo anhelo manifiesto estar...  7885
764  #USER# te amo mucho niña, desearía que tus úni...  1598
..                                                 ...   ...
923  You lived by partial codes. Half measures. Bec...  4894
397  #USER# HAPPY BIRTHDAY HOPE YOU HAVE THE MOST A...  6690
335  RT #USER# Ojalá nunca tengas que dejar ir a al...  2636
661  RT #USER# Deseando leer a liberales defender e...  7655
273  #USER# #USER# Also, as it has been said before...  8197

[2184 rows x 2 columns]

In [ ]:
combined_val.to_csv('val1_data.csv')

In [ ]:
combined_test.to_csv('test1_data.csv')

In [ ]:
combined_train['multiclass'].value_counts()

Not Hope            7789
Generalized Hope    2877
Realistic Hope      1235
Unrealistic Hope    1194
Name: multiclass, dtype: int64

In [ ]:
combined_val['multiclass'].value_counts()

Not Hope            1301
Generalized Hope     486
Realistic Hope       202
Unrealistic Hope     193
Name: multiclass, dtype: int64

In [ ]:
!pip install num2words

In [ ]:
#eemot_object = emot.core.emot()
ps =PorterStemmer()
lemmatiser = WordNetLemmatizer()
english_stopwords = stopwords.words('english, spanish')
exclude = set(string.punctuation)
def preprocess(text):
  text = contractions.fix(text.lower(), slang=True)
  text =re.sub("@ ?[A-Za-z0-9_]+", " ", text)
  text = text.replace('$', ' dollar ')
  text=re.sub(r'$', '', text)
  text= re.sub(r'’','', text )
  text=re.sub('<.*?>','',text)
  text=re.sub(r'http\S+', '', text)
  text = ''.join(ch for ch in text if ch not in exclude)
  tokens = word_tokenize(text)
  #print("Tokens:", tokens)
  text = [t for t in tokens if t not in english_stopwords]
  text = " ".join(text)
  return text

In [ ]:
!pip install inflect

In [ ]:
import inflect
p = inflect.engine()

In [ ]:
def number_to_words(text):
    return ' '.join(p.number_to_words(token) if token.isdigit() else token for token in text.split())

In [ ]:
from nltk.corpus import stopwords, wordnet

In [ ]:
import emoji
#import demoji
#demoji.download_codes()
def emo(text):
  temp=emoji.demojize(text,delimiters=(" "," "))
  temp=temp.replace("_","  ")
  return temp

In [ ]:
combined_train['clean_text']=combined_train["text"].apply(lambda x:emo(x))
combined_train["clean_text"]=combined_train['clean_text'].apply(lambda X: number_to_words(X))
combined_train["clean_text"]=combined_train['clean_text'].apply(lambda X: preprocess(X))

In [ ]:
combined_val['clean_text']=combined_val["text"].apply(lambda x:emo(x))
combined_val["clean_text"]=combined_val['clean_text'].apply(lambda X: number_to_words(X))
combined_val["clean_text"]=combined_val['clean_text'].apply(lambda X: preprocess(X))

In [ ]:
combined_test['clean_text']=combined_test["text"].apply(lambda x:emo(x))
combined_test["clean_text"]=combined_test['clean_text'].apply(lambda X: number_to_words(X))
combined_test["clean_text"]=combined_test['clean_text'].apply(lambda X: preprocess(X))

In [ ]:
df_test_Eng['clean_text']=df_test_Eng["text"].apply(lambda x:emo(x))
df_test_Eng["clean_text"]=df_test_Eng['clean_text'].apply(lambda X: number_to_words(X))
df_test_Eng["clean_text"]=df_test_Eng['clean_text'].apply(lambda X: preprocess(X))

In [ ]:
df_test_span['clean_text']=df_test_span["text"].apply(lambda x:emo(x))
df_test_span["clean_text"]=df_test_span['clean_text'].apply(lambda X: number_to_words(X))
df_test_span["clean_text"]=df_test_span['clean_text'].apply(lambda X: preprocess(X))

In [ ]:
combined_train.head()

text    binary  \
481   I wish more people would block me instead of b...      Hope   
2327  La luna de anoche se veía simplemente hermosa,...      Hope   
5674  Namamen que me entra la llamada que tanto espe...  Not Hope   
3790  #USER# es que el sigue con su vida tan tranqui...  Not Hope   
5933  #USER# Es neta que me hagan esperar más de 45 ...  Not Hope   

            multiclass    id  \
481   Unrealistic Hope  5846   
2327  Generalized Hope  8889   
5674          Not Hope  5734   
3790          Not Hope  6308   
5933          Not Hope  1737   

                                             clean_text  
481   wish people would block instead obsessed fille...  
2327  la luna de anoche se veía simplemente hermosa ...  
5674  namamen que entra la llamada que tanto esperé ...  
3790  user es que el sigue con su vida tan tranquilo...  
5933  user es neta que hagan esperar más de fortyfiv...

In [ ]:
# Move last Column to First Column
new_cols = ["clean_text","multiclass"]
combined_train=combined_train[new_cols]
combined_train

clean_text        multiclass
481   wish people would block instead obsessed fille...  Unrealistic Hope
2327  la luna de anoche se veía simplemente hermosa ...  Generalized Hope
5674  namamen que entra la llamada que tanto esperé ...          Not Hope
3790  user es que el sigue con su vida tan tranquilo...          Not Hope
5933  user es neta que hagan esperar más de fortyfiv...          Not Hope
...                                                 ...               ...
6131  deseando una noche reparadora para tener una s...  Generalized Hope
1126  colorado liberals conservatives hoping remove ...    Realistic Hope
484   motherfucker thirsty white mans approval matte...          Not Hope
4848  user user le creo más un verdadero independien...          Not Hope
901   user user user user user aquí te esperan mucha...  Generalized Hope

[13095 rows x 2 columns]

In [ ]:
# Import label encoder
from sklearn import preprocessing

# label_encoder object knows
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
combined_train['multiclass']= label_encoder.fit_transform(combined_train['multiclass'])

combined_train['multiclass'].unique()

array([3, 0, 1, 2])

In [ ]:
!pip install -U pip wheel
!pip install ensemble-transformers

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/8a/6a/19e9fe04fca059ccf770861c7d5721ab4c2aebc539889e97c7977528a53b/pip-24.0-py3-none-any.whl.metadata
  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl.metadata
  Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Using cached wheel-0.43.0-py3-none-any.whl (65 kB)


ERROR: To modify pip, please run the following command:
C:\Users\User\anaconda3\python.exe -m pip install -U pip wheel


In [ ]:
!git clone https://github.com/jaketae/ensemble-transformers.git
!cd ensemble-transformers
!pip install -e .

'git' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.


Obtaining file:///C:/Users/User/multimodal_Me


ERROR: file:///C:/Users/User/multimodal_Me does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.


In [ ]:
from ensemble_transformers import EnsembleModelForSequenceClassification
ensemble = EnsembleModelForSequenceClassification.from_multiple_pretrained("bert-base-uncased", "distilroberta-base", "xlnet-base-cased")

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at distilroberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of XLNetForSequenceClassification were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: ['logits_proj.bias', 'logits_proj.weight', 'sequence_summary.summary.bias', 'sequence_summary.summary.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for pred

In [ ]:
num_labels = 4

# Optionally, you can pass additional arguments to the ensemble model
args = {
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
    'use_cuda': False  # if you want to disable GPU usage
}

# Create the ensemble model
ensemble.train_model(combined_train, num_labels=num_labels, args=args)

AttributeError: 'EnsembleModelForSequenceClassification' object has no attribute 'train_model'

In [ ]:
# #lxyuan/distilbert-base-multilingual-cased-sentiments-student
# #distilbert/distilroberta-base, distilbert/distilbert-base-uncased
model1 = ClassificationModel('bert', 'google-bert/bert-base-multilingual-cased', num_labels=4, args={'reprocess_input_data': True, 'overwrite_output_dir': True}, use_cuda=False)
model2 = ClassificationModel('bert', 'bert-base-uncased', num_labels=4, args={'reprocess_input_data': True, 'overwrite_output_dir': True}, use_cuda=False)
model3 = ClassificationModel('bert', 'distilbert/distilbert-base-uncased', num_labels=4, args={'reprocess_input_data': True, 'overwrite_output_dir': True}, use_cuda=False)


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at google-bert/bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
You are using a model of type distilbert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at distilbert/distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'embeddings.LayerNorm.bias', 'embeddi

In [ ]:
# Train individual models
model1.train_model(combined_train)
model2.train_model(combined_train)
model3.train_model(combined_train)


C:\Users\User\anaconda3\Lib\site-packages\simpletransformers\classification\classification_model.py:608: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(


  0%|          | 0/26 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 1 of 1:   0%|          | 0/1637 [00:00<?, ?it/s]

C:\Users\User\anaconda3\Lib\site-packages\simpletransformers\classification\classification_model.py:608: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(


  0%|          | 0/26 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 1 of 1:   0%|          | 0/1637 [00:00<?, ?it/s]

  0%|          | 0/26 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 1 of 1:   0%|          | 0/1637 [00:00<?, ?it/s]

(1637, 1.0233979486953069)

In [ ]:
# # Make predictions using individual models
# preds1 = model1.predict(test_df)
# preds2 = model2.predict(test_df)
# preds3 = model3.predict(test_df)

# # Combine predictions using averaging
# ensemble_preds = (preds1 + preds2 + preds3) / 3  # Assuming equal weight for each model

# # Evaluate ensemble predictions
# print(classification_report(test_df['label'], ensemble_preds))


In [ ]:
list_val_text1 = []
for text in combined_val['clean_text']:
  list_val_text1.append(text)


In [ ]:
val_pred1, raw_val_outputs1 = model1.predict(list_val_text1)
val_pred2, raw_val_outputs2 = model2.predict(list_val_text1)
val_pred3, raw_val_outputs3 = model3.predict(list_val_text1)


  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/22 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/22 [00:00<?, ?it/s]

  0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/22 [00:00<?, ?it/s]

In [ ]:
ensemble_preds = (val_pred1 + val_pred2 + val_pred3) / 3  # Assuming equal weight for each model

# # Evaluate ensemble predictions
# print(classification_report(test_df['label'], ensemble_preds))

In [ ]:
val_pred1

array([0, 0, 1, ..., 2, 1, 1], dtype=int64)

In [ ]:
val_pred2

array([0, 1, 1, ..., 2, 1, 1], dtype=int64)

In [ ]:
val_pred3

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [ ]:
import numpy as np

In [ ]:
probmax

3

In [ ]:
import numpy as np

# Assuming num_classes is the number of classes in your dataset (which is 4 in your case)
num_classes = 4

# Convert integer labels to one-hot encoded vectors
def labels_to_one_hot(labels, num_classes):
    return np.eye(num_classes)[labels]

# Convert integer labels to one-hot encoded vectors for each model
one_hot_val_pred1 = labels_to_one_hot(val_pred1, num_classes)
one_hot_val_pred2 = labels_to_one_hot(val_pred2, num_classes)
one_hot_val_pred3 = labels_to_one_hot(val_pred3, num_classes)

# Ensemble the predictions by averaging the one-hot encoded vectors
ensemble_preds = (one_hot_val_pred1 + one_hot_val_pred2 + one_hot_val_pred3) / 3


In [ ]:
ensemble_preds

array([[1.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.66666667, 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       ...,
       [0.33333333, 0.        , 0.66666667, 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ]])

In [ ]:
import numpy as np

# Assuming ensemble_preds is an array containing the ensemble predictions
# Determine the predicted class (label) for each sample
predicted_labels = np.argmax(ensemble_preds, axis=1)


In [ ]:
predicted_labels

array([0, 1, 1, ..., 2, 1, 1], dtype=int64)

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le_fitted = le.fit_transform(combined_val['multiclass'])
inverted = le.inverse_transform(predicted_labels)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(combined_val['multiclass'], inverted))

                  precision    recall  f1-score   support

Generalized Hope       0.52      0.62      0.56       486
        Not Hope       0.79      0.89      0.83      1301
  Realistic Hope       0.38      0.09      0.14       202
Unrealistic Hope       0.55      0.25      0.34       193

        accuracy                           0.70      2182
       macro avg       0.56      0.46      0.47      2182
    weighted avg       0.67      0.70      0.67      2182



In [ ]:
list_test_text1 = []
for text in df_test_span['clean_text']:
  list_test_text1.append(text)

In [ ]:
test_pred1, raw_val_outputs1 = model1.predict(list_test_text1)
test_pred2, raw_val_outputs2 = model2.predict(list_test_text1)
test_pred3, raw_val_outputs3 = model3.predict(list_test_text1)

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

In [ ]:
ensemble_preds = (test_pred1 + test_pred1 + test_pred1) / 3

In [ ]:
import numpy as np

# Assuming num_classes is the number of classes in your dataset (which is 4 in your case)
num_classes = 4

# Convert integer labels to one-hot encoded vectors
def labels_to_one_hot(labels, num_classes):
    return np.eye(num_classes)[labels]

# Convert integer labels to one-hot encoded vectors for each model
one_hot_val_pred4 = labels_to_one_hot(test_pred1, num_classes)
one_hot_val_pred5 = labels_to_one_hot(test_pred2, num_classes)
one_hot_val_pred6 = labels_to_one_hot(test_pred3, num_classes)

# Ensemble the predictions by averaging the one-hot encoded vectors
ensemble_preds_test = (one_hot_val_pred4 + one_hot_val_pred5 + one_hot_val_pred6) / 3

In [ ]:
import numpy as np

# Assuming ensemble_preds is an array containing the ensemble predictions
# Determine the predicted class (label) for each sample
predicted_labels_test = np.argmax(ensemble_preds_test, axis=1)

In [ ]:
predicted_labels_test

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [ ]:
#le_test = le.fit_transform(combined_test['multiclass'])
inverted1 = le.inverse_transform(predicted_labels_test)

In [ ]:
inverted1

array(['Not Hope', 'Not Hope', 'Not Hope', ..., 'Not Hope', 'Not Hope',
       'Not Hope'], dtype=object)

In [ ]:
#Submission
# to create .csv file consisting of tweet ids and predicted labels with CTbert
pred_test = pd.DataFrame(data=inverted1, columns=['Prediction'])
submission_t2 = pd.DataFrame()
submission_t2['id'] = df_test_span['id']
submission_t2['category'] = pred_test
submission_t2.to_csv('EnsembleBert_Span_Multi_data16th.csv', index = None)